epias_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: epias-data-platform  # <-- DİKKAT: Burayı değiştirmelisin!
      dataset: epias_gold
      threads: 4
      keyfile: C:\epias_data_platform\credentials\gcp-key.json
      location: EU  # Veya BigQuery dataset'in US'te ise US yap