# epias_dbt/models/marts/schema.yml
version: 2

models:
  - name: mart_gop_volume_analysis
    description: "GÖP işlem hacimleri ve blok teklif analizleri"
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: ptf_try
        tests:
          - not_null
      - name: total_buy_mwh
        tests:
          - not_null

  - name: mart_ptf_drivers
    description: "PTF tavan/taban sürücüleri ve Yenilenebilir penetrasyonu"
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: renewable_penetration_pct
        tests:
          - dbt_utils.accepted_range: # Yenilenebilir oranı %0 ile %100 arasında olmalıdır
              min_value: 0
              max_value: 100